### ISSUE TITLE
Hyperclient example doesn't work with 0.7.0

### ISSUE THREAD

**Issue by dblock** [artsy/doppler#96]
```
require 'hyperclient'

client_id = '...'
client_secret = '...'

api = Hyperclient.new('https://api.artsy.net/api') do |api|
  api.headers['Accept'] = 'application/vnd.artsy-v2+json'
end

api.tokens.xapp_token._post(client_id: client_id, client_secret: client_secret).token
```

```
Faraday::ClientError: the server responded with status 406
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/response/raise_error.rb:13:in `on_complete'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/hyperclient-0.7.0/lib/hyperclient/link.rb:131:in `block in _post'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/futuroscope-0.1.11/lib/futuroscope/future.rb:39:in `call'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/futuroscope-0.1.11/lib/futuroscope/future.rb:39:in `run_future'
	from /Users/dblock/.rvm/gems/ruby-2.0.0-p598/gems/futuroscope-0.1.11/lib/futuroscope/worker.rb:20:in `block in run'
```

**Comment by dblock** [comment]
Workaround:

```
api = Hyperclient.new('https://api.artsy.net/api') do |api|
  api.headers['Accept'] = 'application/vnd.artsy-v2+json'
  api.headers['Content-type'] = 'application/json'
end
```
